name: Test build

on:
  - pull_request

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      
  prettier:
    name: Test biome
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm ci

    - name: Make biome executable
      run: chmod +x ./node_modules/@biomejs/cli-linux-x64/biome

    - name: Run Prettier
      run: npm run prettier:fix

    - name: Check for changes
      run: git diff --exit-code
